### PR TITLE
Fix: 152 align documentation on nextjs project dir

### LINKED ISSUE #152: nxdev, Could not find a Next.js pages directory.
because it is assumed that the plugin will find the `app` or `pages` directory relative to `process.cwd()`, this plugin doesn't work in a nxdev monorepo.

The solution is to: 

- accept a direct path to the project root.

--- 

edit: 

- [x] update the docs, change `cwd` for `dir` (or update the code to talk about `cwd`)
- [x] generate the types under `dir` (edit: solved with `outdir`)

### PR DESCRIPTION
**Pull request by airtonix**
fixes #152 

- made the `dir` option more obvious in the docs
- disambiguated the problem the `dir` option is solving (it's not unique to nx.dev monorepos)
- started a `Troubleshooting` section to highlight the problem.

### CODE REVIEW

**Comment by airtonix** [comment]
So a few more things: 


- cant install the repo for dev mode, so can't make commits, so had to use `--no-verify`
  - this is caused by the `e2e` directory has a package.json that wants to install a monorepo package (I assume the root package), problem is that the root package is called `nextjs-routes-development` and not `nextjs-routes` like the e2e package wants.
 

Some suggestions: 

- drop nvm. use asdf instead
  - you describe a required pnpm package, asdf can handle this and nodejs for you too.
  - you can provide a bash script like this https://github.com/airtonix/dotfiles/blob/master/commands/files/bin/setup-asdf.bash that people can faceroll all day to get asdf setup (it'll also install all the tools in an [`./.tool-versions`](https://github.com/airtonix/dotfiles/blob/master/devtools/files/asdf/.tool-versions) file).
- restructure the monorepo properly: 
```sh
  package.json
  pnpm-workspace.yaml
  README.md
  pkgs/
    nextjs-routes/
      package.json
    nextjs-routes-e2e/
      package.json
```
- if you cant switch to yarn 4 then use `syncpack` to lint/reformat `package.json` and keep it clean
- use [changesets](https://www.npmjs.com/package/@changesets/cli) to automate changelogs and releases

**Comment by tatethurston** [comment]
> So some unsolictated advice, do with it what you want.
> 
> * cant install the repo for dev mode, so can't make commits, so had to use `--no-verify`
>   
>   * this is caused by the `e2e` directory has a package.json that wants to install a monorepo package (I assume the root package), problem is that the root package is called `nextjs-routes-development` and not `nextjs-routes` like the e2e package wants.
> 
> Some suggestions:
> 
> * drop nvm. use asdf instead
>   
>   * you describe a required pnpm package, asdf can handle this and nodejs for you too.
>   * you can provide a bash script like this https://github.com/airtonix/dotfiles/blob/master/commands/files/bin/setup-asdf.bash that people can faceroll all day to get asdf setup (it'll also install all the tools in an [`./.tool-versions`](https://github.com/airtonix/dotfiles/blob/master/devtools/files/asdf/.tool-versions) file).
> * not sure why the main package.json is called `nextjs-routes-development` ??
> * restructure the monorepo more logically
> 
> ```shell
>   package.json
>   pnpm-workspace.yaml
>   README.md
>   pkgs/
>     nextjs-routes/
>       package.json
>     nextjs-routes-e2e/
>       package.json
> ```
> 
> * drop `prettier-package-json` and switch to yarn4 with some of its linting tools, or if you cant switch to yarn 4 then use `syncpack` to lint/reformat `package.json` and keep it clean
> * use [changesets](https://www.npmjs.com/package/@changesets/cli) to automate changelogs and releases

Thanks, I'll consider these. I haven't had many contributors, so I haven't prioritized documenting local development.

**Comment by airtonix** [comment]
> Thanks @airtonix. A few things:
> 
> 1. The documentation changes reference `cwd`, but this code change renames to `dir`.

😓 😄 woops. it should be `dir` so it's not a breaking change.

> 2. Renaming the configuration option from dir to cwd is a breaking change. I'm open to thinking on a more descriptive name.

👍🏻

**Comment by tatethurston** [comment]
> I just realised that latest version of nextjs has some kind of typesafe routing behind a experimental feature flag: https://beta.nextjs.org/docs/configuring/typescript#statically-typed-links

Yes, I've held off on implementing support for the app directory because Next now supports that natively.

**Comment by tatethurston** [comment]
> 😓 😄 woops. it should be dir so it's not a breaking change.

It's actually the opposite -- it should be `cwd` so that it's non breaking.

**Comment by tatethurston** [comment]
I implemented your suggested change to use the cwd/dir option for the default location for type generation: https://github.com/tatethurston/nextjs-routes/pull/156

**Comment by tatethurston** [comment]
I'm inclined to solve this without any code changes and only update the README.md

**Pull request merged**
