### PR TITLE
all nextjs routes

### PR DESCRIPTION
**Pull request by alinjf**
make a method that return all routes that nextjs app generate.
its uses for sitemaps and schema for seo friendly

### CODE REVIEW

**Comment by tatethurston** [comment]
@alinjf could you tell me more about your intent here? Are you trying to generate a sitemap.xml? Or something different?

**Comment by alinjf** [comment]
yes, i want to do something that i need all routes that is exist in app.
i wanted to generate sitemap.xml and schema.org for seo.

**Comment by tatethurston** [comment]
@alinjf have you checked out https://www.npmjs.com/package/next-sitemap? I suspect there are a few existing npm packages that can accomplish this for you. If not, I’d like to understand what existing npm packages are missing before adding to this library.

**Comment by tatethurston** [comment]
How do you plan to handle dynamic routes for your sitemap? Eg /[foo] ?

**Pull request closed without merging**
