### PR TITLE
Add README notice about Next.js 13 app router statically typed links

### PR DESCRIPTION
**Pull request by mcapodici**
This is a notice for someone who has searched for a solution and found this repo, to tell them they can use a built in feature that may fit their needs.

Although I love the effort that has gone into this project, I think many people will prefer to consider a solution that doesn't need an extra dependency.

### CODE REVIEW

**Comment by mcapodici** [comment]
Related Issue (now closed) https://github.com/tatethurston/nextjs-routes/issues/174

**Comment by tatethurston** [comment]
Thanks @mcapodici

**Comment by tatethurston** [comment]
@mcapodici Does Next's experimental option still only work for the `app` directory, or does it now support pages?

**Comment by mcapodici** [comment]
> @mcapodici Does Next's experimental option still only work for the `app` directory, or does it now support pages?

Looks that way: https://nextjs.org/docs/app/api-reference/next-config-js/typedRoutes

**Pull request merged**
